First attempt to implement a Sqlite db
Moved scraped.sqlite to venv/scraped.sqlite and had to change the gitignore
Tried to use pandas to add the DataFrame to the db but get this error:
__init__() missing 1 required positional argument: 'item_type'